import { HandCoins, Sprout, TriangleAlert, Warehouse } from "lucide-react";
import type { FarmerAction } from "@/domain/types";

interface FarmerActionCardProps {
  action: FarmerAction;
}

const actionIcons = {
  "plant-plan": Sprout,
  "reduce-acreage": HandCoins,
  "secure-buyer": HandCoins,
  "do-not-plant": TriangleAlert,
  "store-if-price": Warehouse,
};

export function FarmerActionCard({ action }: FarmerActionCardProps) {
  const Icon = actionIcons[action.id];
  const stage = action.stage === "before-planting" ? "Before planting" : "At harvest";

  return (
    <section className={`farmer-action farmer-action--${action.id}`} aria-live="polite" aria-label="Recommended next action">
      <div className="farmer-action__icon" aria-hidden="true">
        <Icon size={23} strokeWidth={2.25} />
      </div>
      <div className="farmer-action__content">
        <div className="farmer-action__meta">
          <span>Recommended next action</span>
          <em>{stage}</em>
        </div>
        <h2>{action.title}</h2>
        <ul>
          {action.reasons.slice(0, 3).map((reason) => (
            <li key={reason}>{reason}</li>
          ))}
        </ul>
      </div>
      <p className="farmer-action__trust">Calculated by HarvestWise, not generated by AI.</p>
    </section>
  );
}
